---
title: "Introduction to Statistical Thought"
output: html_notebook
---

# Probability Distributions

```{r}
med.1000 <- read.table('ocean_temps', header = TRUE)

good <- abs ( med.1000$lon + 20 ) < 1 &
        abs ( med.1000$lat - 45 ) < 1

m <- mean ( med.1000$temp[good] )
s <- sqrt ( var ( med.1000$temp[good] ) )

hist ( med.1000$temp[good], xlab="temperature", ylab="",
main="", prob=T, xlim=c(5,11) )

lines ( density(med.1000$temp[good]) )
```

```{r}
hist ( discoveries, xlab="discoveries", ylab="", main="",
prob=T, breaks=seq(-.5,12.5,by=1) )
lines ( 0:12, dpois(0:12, 3.1), type="b" )
```

## The Binomial Distribution

```{r}
data(Titanic)
library(tidyverse)
#help(Titanic)
#summary(Titanic)
#Titanic
```
```{r}
mosaicplot(Titanic, main = "Survival on the Titanic")
```

```{r}
titanicFrame <- as.data.frame(Titanic)
smp <- titanicFrame[sample(nrow(titanicFrame), 30, replace=TRUE, prob = titanicFrame$Freq),]
```


```{r}
nrow(
  titanicFrame[sample(nrow(titanicFrame), 30, replace=TRUE, prob = titanicFrame$Freq),] 
  %>% 
  filter(Survived == "Yes")
)
```
```{r}
result <- 1:5000 %>%
  map_int(function(x)
    nrow(
      titanicFrame[sample(nrow(titanicFrame), 
                          30, 
                          replace=TRUE, 
                          prob = titanicFrame$Freq),] 
      %>% 
      filter(Survived == "Yes")
    )
  )
```

```{r}
hist ( result, xlab="survivors", ylab="", main="",
prob=T, breaks=seq(0,31,by=1) )
lines ( 0:30, dbinom(0:30, 30, 0.323), type="b" )
```

```{r}
totalAll <- (titanicFrame %>% summarise(mean = sum(Freq)))[,c("mean")]
totalSurv <- (titanicFrame %>% filter(Survived == "Yes") %>% summarise(mean = sum(Freq)))[,c("mean")]

totalSurv / totalAll
```

```{r}
selection <- titanicFrame %>% filter(Sex == "Female")
female <- 1:5000 %>%
  map_int(function(x)
    nrow(
      selection[sample(nrow(selection), 
                          30, 
                          replace=TRUE, 
                          prob = selection$Freq),] 
      %>% 
      filter(Survived == "Yes")
    )
  )
```

```{r}
hist ( female, xlab="survivors", ylab="", main="",
prob=T, breaks=seq(0,31,by=1) )
lines ( 0:30, dbinom(0:30, 30, 0.731), type="b" )
```
```{r}
womenAll <- (titanicFrame %>% filter(Sex == "Female") %>% summarise(mean = sum(Freq)))[,c("mean")]
womenSurv <- (titanicFrame %>% filter(Sex == "Female" & Survived == "Yes") %>% summarise(mean = sum(Freq)))[,c("mean")]

womenSurv / womenAll
```


```{r}
selection <- titanicFrame %>% filter(Sex == "Male")
male <- 1:5000 %>%
  map_int(function(x)
    nrow(
      selection[sample(nrow(selection), 
                          30, 
                          replace=TRUE, 
                          prob = selection$Freq),] 
      %>% 
      filter(Survived == "Yes")
    )
  )
```

```{r}
hist ( male, xlab="survivors", ylab="", main="",
prob=T, breaks=seq(0,31,by=1) )
lines ( 0:30, dbinom(0:30, 30, 0.212), type="b" )
```

```{r}
menAll <- (titanicFrame %>% filter(Sex == "Male") %>% summarise(mean = sum(Freq)))[,c("mean")]
menSurv <- (titanicFrame %>% filter(Sex == "Male" & Survived == "Yes") %>% summarise(mean = sum(Freq)))[,c("mean")]

menSurv / menAll
```

```{r}
selection <- titanicFrame %>% filter(Age == "Child")
child <- 1:5000 %>%
  map_int(function(x)
    nrow(
      selection[sample(nrow(selection), 
                          30, 
                          replace=TRUE, 
                          prob = selection$Freq),] 
      %>% 
      filter(Survived == "Yes")
    )
  )
```

```{r}
hist ( child, xlab="survivors", ylab="", main="",
prob=T, breaks=seq(0,31,by=1) )
lines ( 0:30, dbinom(0:30, 30, 0.51), type="b" )
```

```{r}
selection <- titanicFrame %>% filter(Age == "Adult")
adult <- 1:5000 %>%
  map_int(function(x)
    nrow(
      selection[sample(nrow(selection), 
                          30, 
                          replace=TRUE, 
                          prob = selection$Freq),] 
      %>% 
      filter(Survived == "Yes")
    )
  )
```

```{r}
hist ( adult, xlab="survivors", ylab="", main="",
prob=T, breaks=seq(0,31,by=1) )
lines ( 0:30, dbinom(0:30, 30, 0.3), type="b" )
```

```{r}
selection <- titanicFrame %>% filter(Class == "Crew")
crew <- 1:5000 %>%
  map_int(function(x)
    nrow(
      selection[sample(nrow(selection), 
                          30, 
                          replace=TRUE, 
                          prob = selection$Freq),] 
      %>% 
      filter(Survived == "Yes")
    )
  )
```
```{r}
hist ( crew, xlab="survivors", ylab="", main="",
prob=T, breaks=seq(0,31,by=1) )
lines ( 0:30, dbinom(0:30, 30, 0.225), type="b" )
```
```{r}
selection <- titanicFrame %>% filter(Class == "1st")
fstCls <- 1:5000 %>%
  map_int(function(x)
    nrow(
      selection[sample(nrow(selection), 
                          30, 
                          replace=TRUE, 
                          prob = selection$Freq),] 
      %>% 
      filter(Survived == "Yes")
    )
  )
```
```{r}
hist ( fstCls, xlab="survivors", ylab="", main="",
prob=T, breaks=seq(0,31,by=1) )
lines ( 0:30, dbinom(0:30, 30, 0.61), type="b" )
```

```{r}
combined<-data.frame(dataset=c(rep('Adults',length(adult)),rep('Child',length(child))),value=c(adult,child))
ggplot(combined,aes(x=value,fill=dataset)) +
  geom_histogram(aes(y=0.5*..density..),
                 alpha=0.5,position='identity',binwidth=1)
```


# The Rest

* Uniform distribution.
* The Poisson Distribution
* The Exponential Distribution
* The Normal Distribution
* CENTERS, SPREADS, MEANS, AND MOMENTS
* Association, Dependence, Independence

